In [1]:
print('all  ok ')


all  ok 


In [10]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

In [4]:
documents = ["people watch movies",
             "people like movies",
             "people like music",
             "people watch music"]

In [6]:
tokens = [sentence.lower().split() for sentence in documents]
print(tokens)

[['people', 'watch', 'movies'], ['people', 'like', 'movies'], ['people', 'like', 'music'], ['people', 'watch', 'music']]


In [8]:
all_words = [word for sentence in tokens for word in sentence]
print(all_words)
unique_words = set(all_words)
print(unique_words)


['people', 'watch', 'movies', 'people', 'like', 'movies', 'people', 'like', 'music', 'people', 'watch', 'music']
{'music', 'like', 'movies', 'watch', 'people'}


In [12]:
encoder = OneHotEncoder(sparse_output=False)
# encoder.fit(all_words)

In [15]:
encoder.fit(np.array(all_words).reshape(-1, 1))


OneHotEncoder(sparse_output=False)

In [16]:
print("vocabulary:", encoder.categories_[0])

vocabulary: ['like' 'movies' 'music' 'people' 'watch']


In [19]:


for sentence in tokens:
    encoded_sentence = encoder.transform(np.array(sentence).reshape(-1, 1))
    print(sentence)
    print(encoded_sentence)

['people', 'watch', 'movies']
[[0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0.]]
['people', 'like', 'movies']
[[0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]]
['people', 'like', 'music']
[[0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]
['people', 'watch', 'music']
[[0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0.]]


In [ ]:
#Bag of words

#Bag or words captures how frequently a word us used in a meaningful way. 


# Based on the count of words. word occurence in a document is more then it is more important.

# some of the examples of the bag of words are below: 

#vocabulary: ['like' 'movies' 'music' 'people' 'watch']. ==> unique words in the document.

#if we preprocess we will remove words like 'a' , 'the' , 'is' etc. these are called stop words.

In [21]:
from sklearn.feature_extraction.text import CountVectorizer


In [27]:
documents = ["people watch movies and music",
             "people like movies and like music",
             "people like music and watch music and watch cricket",
             "people watch music like cricket watch movies"]

In [28]:
bow = CountVectorizer()
bow_transformed = bow.fit_transform(documents)
print("vocabulary:", bow.get_feature_names_out())
print(bow_transformed.toarray())


vocabulary: ['and' 'cricket' 'like' 'movies' 'music' 'people' 'watch']
[[1 0 0 1 1 1 1]
 [1 0 2 1 1 1 0]
 [2 1 1 0 2 1 2]
 [0 1 1 1 1 1 2]]


In [29]:
vocab = bow.get_feature_names_out()
matrix = bow_transformed.toarray()

print("Vocabulary:", vocab)
print("\nBag-of-words matrix (rows=document, columns=word counts):")
print(matrix)

for i, doc in enumerate(documents):
    print(f"\nDocument {i+1}: {doc}")
    for word, count in zip(vocab, matrix[i]):
        if count > 0:
            print(f"  {word}: {count}")

Vocabulary: ['and' 'cricket' 'like' 'movies' 'music' 'people' 'watch']

Bag-of-words matrix (rows=document, columns=word counts):
[[1 0 0 1 1 1 1]
 [1 0 2 1 1 1 0]
 [2 1 1 0 2 1 2]
 [0 1 1 1 1 1 2]]

Document 1: people watch movies and music
  and: 1
  movies: 1
  music: 1
  people: 1
  watch: 1

Document 2: people like movies and like music
  and: 1
  like: 2
  movies: 1
  music: 1
  people: 1

Document 3: people like music and watch music and watch cricket
  and: 2
  cricket: 1
  like: 1
  music: 2
  people: 1
  watch: 2

Document 4: people watch music like cricket watch movies
  cricket: 1
  like: 1
  movies: 1
  music: 1
  people: 1
  watch: 2


#TF-IDF

#(Term Frequency - Inverse Document Frequency) is a statistical measure used to evaluate the importance of a word 
#in a document relative to a collection of documents (corpus). 
#It helps to identify words that are more relevant to a specific document while downplaying common words that appear frequently across all documents.

In [ ]:
TF(Word, D) = (Occurrences of the word in the sentencec) / (total words in the given sentence)

IDF(Word) = log(Total number of sentence / Number of sentence containing the word)

In [31]:

from sklearn.feature_extraction.text import TfidfVectorizer

new_documents = [
    "machine learning helps computers learn from data",
    "deep learning is a subset of machine learning",
    "natural language processing works with text DATA",
    "data science uses statistics and machine learning"
]

tfidf = TfidfVectorizer()
tfidf_matrix = tfidf.fit_transform(new_documents)

print("Vocabulary:", tfidf.get_feature_names_out())
print("\nTF-IDF matrix:")
print(tfidf_matrix.toarray())

for i, doc in enumerate(new_documents):
    print(f"\nDocument {i+1}: {doc}")
    for word, score in zip(tfidf.get_feature_names_out(), tfidf_matrix.toarray()[i]):
        if score > 0:
            print(f"  {word}: {score:.3f}")

Vocabulary: ['and' 'computers' 'data' 'deep' 'from' 'helps' 'is' 'language' 'learn'
 'learning' 'machine' 'natural' 'of' 'processing' 'science' 'statistics'
 'subset' 'text' 'uses' 'with' 'works']

TF-IDF matrix:
[[0.         0.4375946  0.27931097 0.         0.4375946  0.4375946
  0.         0.         0.4375946  0.27931097 0.27931097 0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.        ]
 [0.         0.         0.         0.40699357 0.         0.
  0.40699357 0.         0.         0.51955745 0.25977872 0.
  0.40699357 0.         0.         0.         0.40699357 0.
  0.         0.         0.        ]
 [0.         0.         0.25215917 0.         0.         0.
  0.         0.39505606 0.         0.         0.         0.39505606
  0.         0.39505606 0.         0.         0.         0.39505606
  0.         0.39505606 0.39505606]
 [0.4375946  0.         0.27931097 0.         0.         0.
  0.         0.         0.         0.27931097 0.27931097